site_name: Tritan
theme:
  name: material
  custom_dir: 'theme'
  palette:
    primary: blue
    accent: blue
  favicon: 'img/favicon.ico'
  logo:
    icon: 'account_balance'
repo_name: 'tapanther/Tritan'
repo_url: 'https://github.com/tapanther/Tritan'
site_url: 'https://tapanther.github.io/Tritan/'

extra:
  disqus: 'tritan'

markdown_extensions:
  - admonition
  - pymdownx.superfences

nav:
  - Home : index.md
  - Campaign :
    - Emerald Tablets : EmeraldTablet_GM.md
    - Murder on the Stonhyr Express : MurderOnTheStonhyrExpress.md
    - The Demon Core : DemonCore_GM.md
  - General :
    - Timeline : Timeline.md
  - Categories :
      - Campaign : Campaign.md
      - General : General.md
