{% import 'macros.md' as macros with context %}
site_name: Tritan
theme:
  name: material
  custom_dir: 'theme'
  palette:
    primary: blue
    accent: blue
  favicon: 'img/favicon.ico'
  logo:
    icon: 'account_balance'
repo_name: 'tapanther/Tritan'
repo_url: 'https://github.com/tapanther/Tritan'
site_url: 'https://tapanther.github.io/Tritan/'

extra:
  disqus: 'tritan'

extra_css:
  - stylesheets/uml.css
  
extra_javascript:
  - js/uml.js
  - js/mermaid.min.js
#  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.4.6/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.9.1/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.13.0/flowchart.min.js

markdown_extensions:
  - admonition
  - pymdownx.superfences :
      custom_fences :
        - name : flow
          class : uml-flowchart
          format : !!python/name:pymdownx.superfences.fence_div_format
        - name : sequence
          class : uml-sequence-diagram
          format : !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

nav:
  - Home : index.md
{% for child in navTree|getTreeDirectChildren if not child.noLink %}
{{ macros.printTreeYAML(child, 1) }}
{%- endfor %}
  - Categories :
{% for child in navTree.children | sort_multi('parent', 'name') if (not child.noLink and child.children) %}
      - {{ child.name }} : {{ child.file }}
{% endfor %}
