{% import 'macros.md' as macros with context %}
site_name: Tritan
theme:
  name: material
  custom_dir: 'theme'
  palette:
    primary: blue
    accent: blue
  favicon: 'img/favicon.ico'
  logo:
    icon: 'account_balance'
repo_name: 'tapanther/Tritan'
repo_url: 'https://github.com/tapanther/Tritan'
site_url: 'https://tapanther.github.io/Tritan/'

extra:
  disqus: 'tritan'

markdown_extensions:
  - admonition
  - pymdownx.superfences

nav:
  - Home : index.md
{% for child in navTree|getTreeDirectChildren if not child.noLink %}
{{ macros.printTreeYAML(child, 1) }}
{%- endfor %}
  - Categories :
{% for child in navTree.children | sort_multi('parent', 'name') if (not child.noLink and child.children) %}
      - {{ child.name }} : {{ child.file }}
{% endfor %}
